sudo: false
language: node_js
node_js:
  - '5'
  - '4'
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
addons:
    codecov:
        repo_token: 588523da-e23c-466d-9e73-bf1f47e80bdd
