
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "stable"
sudo: false
script: "gulp coverage"
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
    codecov: 7f03c8d8-8145-463f-b20e-f4e5eccecf6c
