sudo: false
language: node_js
node_js:
  - '5'
  - '4'
script:
  - npm run test:cover
after_success:
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
addons:
    codecov:
        repo_token: 7f03c8d8-8145-463f-b20e-f4e5eccecf6c
